### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by TacoTheDank**
### 1st commit
- Update gradle wrapper to 6.8 using git bash

### 2nd commit
- Reorganize and clean up the build gradles

### 3rd commit
- Update NDK 21.3 -> 22.0 ([changelog](https://github.com/android/ndk/wiki/Changelog-r22))
- Update Dagger 2.28 -> 2.31.2 ([changelog](https://github.com/google/dagger/releases))
- Update JUnit 4.13 -> 4.13.1 ([changelog](https://github.com/junit-team/junit4/blob/HEAD/doc/ReleaseNotes4.13.1.md))
- Update minimum CMake 3.4.1 -> 3.10.2
- Update Undercouch plugin 4.0.0 -> 4.1.1 ([changelog](https://github.com/michel-kraemer/gradle-download-task/releases))

### 4th commit
- Use some KTX extensions

### 5th commit
- Clean up some Kotlin stuff

### 6th commit
- Migrate to help page to ViewPager2 (see [here](https://developer.android.com/training/animation/vp2-migration))

### 7th commit
- Regenerate (to latest material design) and rename drawables

### CODE REVIEW

**Comment by btimofeev** [comment]
Thank you!

**Comment by TacoTheDank** [comment]
@btimofeev Thanks for merging!

A small side note relating to your inversion commit [here](https://github.com/btimofeev/UniPatcher/commit/2e4bd624effeb2f97d802fd1cfe7199fa6ebbd4d), I chose to do the double negative because while `isInvisible` returns either invisible or visible, `isVisible` returns either visible or gone. Just wanted to make sure your change is actually intentional, since the view being gone means space for it is no longer reserved despite not being there (while the original code had it simply being [invisible](https://github.com/btimofeev/UniPatcher/pull/49/commits/14ec10a8f5ec203e48c538e8defbb0cb175b8108#diff-bf7497437e04c4d092e3e06be3700b64d2403b6ba9c739a02f0c4ad915f39007L79)) :)

**Comment by btimofeev** [comment]
@TacoTheDank Yes, I got it. Both GONE and INVISIBLE are suitable for current layouts. The code is easier to read without inversion, so I fixed it.

**Comment by TacoTheDank** [comment]
@btimofeev Alright, thanks for responding :)

**Pull request merged**
